### ISSUE TITLE
Disable when dead

### ISSUE THREAD

**Issue by iSentrie** [bepo13/FiveM-RadialMenu#3]
How to disable it when player is dead?

Doesnt work to just

        return IsPlayerDead(player, false)
or

       return IsPedOnFoot(player) and IsPlayerDead(player, false)
Any ideas?

**Comment by FrenchBoomer** [comment]
Still looking for this?

**Comment by iSentrie** [comment]
yeah

**Comment by ali-exacute** [comment]
> 
> 
> How to disable it when player is dead?
> 
> Doesnt work to just
> 
> ```
>     return IsPlayerDead(player, false)
> ```
> 
> or
> 
> ```
>    return IsPedOnFoot(player) and IsPlayerDead(player, false)
> ```
> 
> Any ideas?

`return IsPedOnFoot(player) and not IsPedDeadOrDying(player, 1)`
